package service.network

enum class ConnectionState {
    DISCONNECTED,
    CONNECTED,
    WAITING_FOR_HOST_CONFIRMATION,
    WAITING_FOR_JOIN_CONFIRMATION,
    WAITING_FOR_GUESTS,
    WAITING_FOR_INIT,
    PLAYING_MY_TURN,
    WAITING_FOR_OPPONENT
}